### ISSUE TITLE
grafana pods crashing 

### ISSUE THREAD

**Issue by novonilc** [debianmaster/openshift-examples#19]
Grafana containers are crashing with following error : 

chown: changing ownership of '/var/lib/grafana': Operation not permitted

**Comment by debianmaster** [comment]
sorry for the delay.
did you do this `oc adm policy add-scc-to-user anyuid -z default` ?   on the namespace where you are deploying

**Comment by lannyMa** [comment]
# the grafana pod is crash!!!
t=2017-05-15T11:50:14+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory%!(EXTRA []interface {}=[])"

**Comment by lannyMa** [comment]
oh i fixed it , i just repeat again

**Comment by debianmaster** [comment]
cool closing this.
