### ISSUE TITLE
waitting for u new video

### ISSUE THREAD

**Issue by lannyMa** [debianmaster/openshift-examples#21]
# waitting for u new video; very thx

**Comment by debianmaster** [comment]
which topic :) ?

**Comment by lannyMa** [comment]
- about the scc sa rolebings etc.. the authorization is not clear,because there is so much role and rolebings in openshift  and i donot kown which case i would use which role or rolebings, I think you should list some common case

- the ci or cd in openshift jenkins. one of your video is much old and i want to kown the newest version of openshift combine with jenkins, it is better  form a jenkins cluster inside to openshift. 

- the alarm of Prometheus, i can install it ,but i donot kown how to use it,for example what case should i  use alertmanager

- the data persistent, how is the Prometheus and jenkins data to persistent. and should it is necessary. and statefulset persistent is confused, cannot think clearly.

**Comment by debianmaster** [comment]
I'm planning for few videos. but none of these topics are in the radar.   i will do if i find additional time.   thanks for following @lannyMa

**Comment by lannyMa** [comment]
thks a lot.
