### ISSUE TITLE
Knative install - updated instructions

### ISSUE THREAD

**Issue by marcredhat** [debianmaster/openshift-examples#85]
https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml
no longer exists.

I successfully tested as follows:
curl -L https://github.com/knative/serving/releases/download/v0.2.3/release-lite.yaml  | sed 's/LoadBalancer/NodePort/'   | oc apply -f -

**Comment by debianmaster** [comment]
thanks for this info, i have now changed notes to reflect this.
